AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  ${{ values.description }}

Parameters:
  Domain:
    Type: String
    Description: 'Application Platform'

  System:
    Type: String
    Description: 'Application System'

  Component:
    Type: String
    Description: 'Application Component'

  CodeBranch:
    Type: String
    Description: "Name of deployment branch"

Globals:
  Function:
    Runtime: python${{ values.python_version }}
    Timeout: 5
    MemorySize: 128
    Environment:
      Variables:
        DDB_TABLE_NAME: !Ref DdbTable
        POWERTOOLS_SERVICE_NAME: !Ref AWS::StackName


Resources:
  # Functions
  ${{ values.function_name }}Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handlers/${{ values.function_name }}
      Handler: function.handler
      {% if values.function_description -%}
      Description: ${{ values.function_description }}
      {%- endif %}
